colnames = ["Strength", "Agility", "Intelligence"]
thumbs = [[[
   {'id': 7,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_sb.png',
    'name': 'Earthshaker'},
   {'id': 18,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/sven_sb.png',
    'name': 'Sven'},
   {'id': 19,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/tiny_sb.png',
    'name': 'Tiny'},
   {'id': 23,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_sb.png',
    'name': 'Kunkka'},
   {'id': 38,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_sb.png',
    'name': 'Beastmaster'},
   {'id': 49,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_sb.png',
    'name': 'Dragon Knight'},
   {'id': 51,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_sb.png',
    'name': 'Clockwerk'},
   {'id': 57,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_sb.png',
    'name': 'Omniknight'},
   {'id': 59,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/huskar_sb.png',
    'name': 'Huskar'},
   {'id': 73,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_sb.png',
    'name': 'Alchemist'},
   {'id': 78,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/brewmaster_sb.png',
    'name': 'Brewmaster'},
   {'id': 83,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/treant_sb.png',
    'name': 'Treant Protector'},
   {'id': 91,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/wisp_sb.png',
    'name': 'Io'},
   {'id': 96,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/centaur_sb.png',
    'name': 'Centaur Warrunner'},
   {'id': 98,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/shredder_sb.png',
    'name': 'Timbersaw'},
   {'id': 99,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/bristleback_sb.png',
    'name': 'Bristleback'},
   {'id': 100,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/tusk_sb.png',
    'name': 'Tusk'},
   {'id': 103,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/elder_titan_sb.png',
    'name': 'Elder Titan'},
   {'id': 104,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/legion_commander_sb.png',
    'name': 'Legion Commander'},
   {'id': 107,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/earth_spirit_sb.png',
    'name': 'Earth Spirit'},
   {'id': 110,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/phoenix_sb.png',
    'name': 'Phoenix'}],
  [{'id': 2,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/axe_sb.png',
    'name': 'Axe'},
   {'id': 14,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/pudge_sb.png',
    'name': 'Pudge'},
   {'id': 16,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_sb.png',
    'name': 'Sand King'},
   {'id': 28,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/slardar_sb.png',
    'name': 'Slardar'},
   {'id': 29,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_sb.png',
    'name': 'Tidehunter'},
   {'id': 42,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/skeleton_king_sb.png',
    'name': 'Wraith King'},
   {'id': 54,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/life_stealer_sb.png',
    'name': 'Lifestealer'},
   {'id': 60,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/night_stalker_sb.png',
    'name': 'Night Stalker'},
   {'id': 69,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_sb.png',
    'name': 'Doom'},
   {'id': 71,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/spirit_breaker_sb.png',
    'name': 'Spirit Breaker'},
   {'id': 77,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/lycan_sb.png',
    'name': 'Lycan'},
   {'id': 81,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_sb.png',
    'name': 'Chaos Knight'},
   {'id': 85,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/undying_sb.png',
    'name': 'Undying'},
   {'id': 97,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/magnataur_sb.png',
    'name': 'Magnus'},
   {'id': 102,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_sb.png',
    'name': 'Abaddon'}]],
 [[{'id': 1,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/antimage_sb.png',
    'name': 'Anti-Mage'},
   {'id': 6,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_sb.png',
    'name': 'Drow Ranger'},
   {'id': 8,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_sb.png',
    'name': 'Juggernaut'},
   {'id': 9,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/mirana_sb.png',
    'name': 'Mirana'},
   {'id': 10,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/morphling_sb.png',
    'name': 'Morphling'},
   {'id': 12,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_lancer_sb.png',
    'name': 'Phantom Lancer'},
   {'id': 20,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/vengefulspirit_sb.png',
    'name': 'Vengeful Spirit'},
   {'id': 32,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/riki_sb.png',
    'name': 'Riki'},
   {'id': 35,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/sniper_sb.png',
    'name': 'Sniper'},
   {'id': 46,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_sb.png',
    'name': 'Templar Assassin'},
   {'id': 48,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/luna_sb.png',
    'name': 'Luna'},
   {'id': 62,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_sb.png',
    'name': 'Bounty Hunter'},
   {'id': 70,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/ursa_sb.png',
    'name': 'Ursa'},
   {'id': 72,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_sb.png',
    'name': 'Gyrocopter'},
   {'id': 80,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_sb.png',
    'name': 'Lone Druid'},
   {'id': 89,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/naga_siren_sb.png',
    'name': 'Naga Siren'},
   {'id': 95,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_sb.png',
    'name': 'Troll Warlord'},
   {'id': 106,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/ember_spirit_sb.png',
    'name': 'Ember Spirit'}],
  [{'id': 4,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/bloodseeker_sb.png',
    'name': 'Bloodseeker'},
   {'id': 11,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_sb.png',
    'name': 'Shadow Fiend'},
   {'id': 15,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/razor_sb.png',
    'name': 'Razor'},
   {'id': 40,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_sb.png',
    'name': 'Venomancer'},
   {'id': 41,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/faceless_void_sb.png',
    'name': 'Faceless Void'},
   {'id': 44,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_sb.png',
    'name': 'Phantom Assassin'},
   {'id': 47,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/viper_sb.png',
    'name': 'Viper'},
   {'id': 56,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/clinkz_sb.png',
    'name': 'Clinkz'},
   {'id': 61,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/broodmother_sb.png',
    'name': 'Broodmother'},
   {'id': 63,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/weaver_sb.png',
    'name': 'Weaver'},
   {'id': 67,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/spectre_sb.png',
    'name': 'Spectre'},
   {'id': 82,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/meepo_sb.png',
    'name': 'Meepo'},
   {'id': 88,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/nyx_assassin_sb.png',
    'name': 'Nyx Assassin'},
   {'id': 93,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/slark_sb.png',
    'name': 'Slark'},
   {'id': 94,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/medusa_sb.png',
    'name': 'Medusa'},
   {'id': 109,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_sb.png',
    'name': 'Terrorblade'},
   {'id': 113,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/arc_warden_sb.png',
    'name': 'Arc Warden'}]],
 [[{'id': 5,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_sb.png',
    'name': 'Crystal Maiden'},
   {'id': 13,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/puck_sb.png',
    'name': 'Puck'},
   {'id': 17,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/storm_spirit_sb.png',
    'name': 'Storm Spirit'},
   {'id': 21,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_sb.png',
    'name': 'Windranger'},
   {'id': 22,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/zuus_sb.png',
    'name': 'Zeus'},
   {'id': 25,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/lina_sb.png',
    'name': 'Lina'},
   {'id': 27,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_sb.png',
    'name': 'Shadow Shaman'},
   {'id': 34,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/tinker_sb.png',
    'name': 'Tinker'},
   {'id': 53,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/furion_sb.png',
    'name': "Nature\'s Prophet"},
   {'id': 58,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_sb.png',
    'name': 'Enchantress'},
   {'id': 64,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/jakiro_sb.png',
    'name': 'Jakiro'},
   {'id': 66,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/chen_sb.png',
    'name': 'Chen'},
   {'id': 75,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/silencer_sb.png',
    'name': 'Silencer'},
   {'id': 84,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_sb.png',
    'name': 'Ogre Magi'},
   {'id': 86,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/rubick_sb.png',
    'name': 'Rubick'},
   {'id': 87,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_sb.png',
    'name': 'Disruptor'},
   {'id': 90,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_sb.png',
    'name': 'Keeper of the Light'},
   {'id': 101,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/skywrath_mage_sb.png',
    'name': 'Skywrath Mage'},
   {'id': 111,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/oracle_sb.png',
    'name': 'Oracle'},
   {'id': 105,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/techies_sb.png',
    'name': 'Techies'}],
  [{'id': 3,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/bane_sb.png',
    'name': 'Bane'},
   {'id': 31,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/lich_sb.png',
    'name': 'Lich'},
   {'id': 26,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/lion_sb.png',
    'name': 'Lion'},
   {'id': 30,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_sb.png',
    'name': 'Witch Doctor'},
   {'id': 33,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/enigma_sb.png',
    'name': 'Enigma'},
   {'id': 36,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_sb.png',
    'name': 'Necrophos'},
   {'id': 37,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/warlock_sb.png',
    'name': 'Warlock'},
   {'id': 39,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_sb.png',
    'name': 'Queen of Pain'},
   {'id': 43,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/death_prophet_sb.png',
    'name': 'Death Prophet'},
   {'id': 45,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/pugna_sb.png',
    'name': 'Pugna'},
   {'id': 50,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/dazzle_sb.png',
    'name': 'Dazzle'},
   {'id': 52,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/leshrac_sb.png',
    'name': 'Leshrac'},
   {'id': 55,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/dark_seer_sb.png',
    'name': 'Dark Seer'},
   {'id': 65,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/batrider_sb.png',
    'name': 'Batrider'},
   {'id': 68,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/ancient_apparition_sb.png',
    'name': 'Ancient Apparition'},
   {'id': 74,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/invoker_sb.png',
    'name': 'Invoker'},
   {'id': 76,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/obsidian_destroyer_sb.png',
    'name': 'Outworld Devourer'},
   {'id': 79,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_demon_sb.png',
    'name': 'Shadow Demon'},
   {'id': 92,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/visage_sb.png',
    'name': 'Visage'},
   {'id': 112,
    'img': 'http://cdn.dota2.com/apps/dota2/images/heroes/winter_wyvern_sb.png',
    'name': 'Winter Wyvern'}]]]




# thumbs_small = [
#     ['http://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_sb.png', 
#     'http://cdn.dota2.com/apps/dota2/images/heroes/sven_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/tiny_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/huskar_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/brewmaster_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/treant_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/wisp_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/centaur_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/shredder_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/bristleback_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/tusk_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/elder_titan_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/legion_commander_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/earth_spirit_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/phoenix_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/axe_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/pudge_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/slardar_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/skeleton_king_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/life_stealer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/night_stalker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/spirit_breaker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lycan_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/undying_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/magnataur_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/antimage_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/mirana_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/morphling_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_lancer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/vengefulspirit_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/riki_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/sniper_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/luna_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/ursa_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/naga_siren_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/ember_spirit_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/bloodseeker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/razor_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/faceless_void_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/viper_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/clinkz_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/broodmother_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/weaver_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/spectre_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/meepo_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/nyx_assassin_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/slark_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/medusa_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/arc_warden_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/puck_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/storm_spirit_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/zuus_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lina_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/tinker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/furion_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/jakiro_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/chen_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/silencer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/rubick_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/skywrath_mage_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/oracle_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/techies_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/bane_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lich_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lion_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/enigma_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/warlock_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/death_prophet_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/pugna_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/dazzle_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/leshrac_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/dark_seer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/batrider_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/ancient_apparition_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/invoker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/obsidian_destroyer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_demon_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/visage_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/winter_wyvern_sb.png']]
# thumbs = [
#     ['http://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_sb.png', 
#     'http://cdn.dota2.com/apps/dota2/images/heroes/sven_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/tiny_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/huskar_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/brewmaster_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/treant_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/wisp_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/centaur_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/shredder_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/bristleback_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/tusk_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/elder_titan_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/legion_commander_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/earth_spirit_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/phoenix_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/axe_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/pudge_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/slardar_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/skeleton_king_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/life_stealer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/night_stalker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/spirit_breaker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lycan_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/undying_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/magnataur_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/antimage_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/mirana_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/morphling_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_lancer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/vengefulspirit_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/riki_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/sniper_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/luna_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/ursa_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/naga_siren_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/ember_spirit_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/bloodseeker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/razor_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/faceless_void_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/viper_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/clinkz_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/broodmother_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/weaver_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/spectre_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/meepo_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/nyx_assassin_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/slark_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/medusa_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/arc_warden_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/puck_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/storm_spirit_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/zuus_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lina_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/tinker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/furion_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/jakiro_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/chen_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/silencer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/rubick_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/skywrath_mage_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/oracle_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/techies_sb.png'], ['http://cdn.dota2.com/apps/dota2/images/heroes/bane_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lich_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/lion_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/enigma_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/warlock_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/death_prophet_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/pugna_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/dazzle_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/leshrac_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/dark_seer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/batrider_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/ancient_apparition_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/invoker_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/obsidian_destroyer_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_demon_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/visage_sb.png', 'http://cdn.dota2.com/apps/dota2/images/heroes/winter_wyvern_sb.png']]

# thumbids = [
#     [7, 18, 19, 23, 38, 49, 51, 57, 59, 73, 78, 83, 91, 96, 98, 99, 100, 103, 104, 107, 110], 
#     [2, 14, 16, 28, 29, 42, 54, 60, 69, 71, 77, 81, 85, 97, 102], 
#     [1, 6, 8, 9, 10, 12, 20, 32, 35, 46, 48, 62, 70, 72, 80, 89, 95, 106], 
#     [4, 11, 15, 40, 41, 44, 47, 56, 61, 63, 67, 82, 88, 93, 94, 109, 113], 
#     [5, 13, 17, 21, 22, 25, 27, 34, 53, 58, 64, 66, 75, 84, 86, 87, 90, 101, 111, 105], 
#     [3, 31, 26, 30, 33, 36, 37, 39, 43, 45, 50, 52, 55, 65, 68, 74, 76, 79, 92, 112]]

# thumbnames = [['Earthshaker',
#   'Sven',
#   'Tiny',
#   'Kunkka',
#   'Beastmaster',
#   'Dragon Knight',
#   'Clockwerk',
#   'Omniknight',
#   'Huskar',
#   'Alchemist',
#   'Brewmaster',
#   'Treant Protector',
#   'Io',
#   'Centaur Warrunner',
#   'Timbersaw',
#   'Bristleback',
#   'Tusk',
#   'Elder Titan',
#   'Legion Commander',
#   'Earth Spirit',
#   'Phoenix'],
#  ['Axe',
#   'Pudge',
#   'Sand King',
#   'Slardar',
#   'Tidehunter',
#   'Wraith King',
#   'Lifestealer',
#   'Night Stalker',
#   'Doom',
#   'Spirit Breaker',
#   'Lycan',
#   'Chaos Knight',
#   'Undying',
#   'Magnus',
#   'Abaddon'],
#  ['Anti-Mage',
#   'Drow Ranger',
#   'Juggernaut',
#   'Mirana',
#   'Morphling',
#   'Phantom Lancer',
#   'Vengeful Spirit',
#   'Riki',
#   'Sniper',
#   'Templar Assassin',
#   'Luna',
#   'Bounty Hunter',
#   'Ursa',
#   'Gyrocopter',
#   'Lone Druid',
#   'Naga Siren',
#   'Troll Warlord',
#   'Ember Spirit'],
#  ['Bloodseeker',
#   'Shadow Fiend',
#   'Razor',
#   'Venomancer',
#   'Faceless Void',
#   'Phantom Assassin',
#   'Viper',
#   'Clinkz',
#   'Broodmother',
#   'Weaver',
#   'Spectre',
#   'Meepo',
#   'Nyx Assassin',
#   'Slark',
#   'Medusa',
#   'Terrorblade',
#   'Arc Warden'],
#  ['Crystal Maiden',
#   'Puck',
#   'Storm Spirit',
#   'Windranger',
#   'Zeus',
#   'Lina',
#   'Shadow Shaman',
#   'Tinker',
#   "Nature's Prophet",
#   'Enchantress',
#   'Jakiro',
#   'Chen',
#   'Silencer',
#   'Ogre Magi',
#   'Rubick',
#   'Disruptor',
#   'Keeper of the Light',
#   'Skywrath Mage',
#   'Oracle',
#   'Techies'],
#  ['Bane',
#   'Lich',
#   'Lion',
#   'Witch Doctor',
#   'Enigma',
#   'Necrophos',
#   'Warlock',
#   'Queen of Pain',
#   'Death Prophet',
#   'Pugna',
#   'Dazzle',
#   'Leshrac',
#   'Dark Seer',
#   'Batrider',
#   'Ancient Apparition',
#   'Invoker',
#   'Outworld Devourer',
#   'Shadow Demon',
#   'Visage',
#   'Winter Wyvern']]



# thumbzip = [list(zip(thumbs[i], thumbids[i], thumbnames[i])) for i in range(len(thumbs))]
# thumbzip = [[thumbzip[0], thumbzip[1]], [thumbzip[2], thumbzip[3]], [thumbzip[4], thumbzip[5]]]
# thumbargs = [[[{"img": herothumb[0], "id": herothumb[1], "name": herothumb[2]} for herothumb in group] for group in col] for col in thumbzip]

